### ISSUE TITLE
nightly-2017-12-10.yaml

### ISSUE THREAD

**Issue by MarianJancar** [commercialhaskell/stackage-nightly#1]
Downloaded nightly-2017-12-10 build plan.    
AesonException "Error in $.packages.cassava.constraints.flags['bytestring--lt-0_10_4']: Invalid flag name: \"bytestring--lt-0_10_4\""

**Comment by snoyberg** [comment]
Please upgrade to Stack 1.6.1 by running `stack upgrade`.

**Comment by MarianJancar** [comment]
thank you
