### ISSUE TITLE
Error install haskell-ide-engine: Unable to load cabal files for snapshot,  see screenshot

### ISSUE THREAD

**Issue by wanggang1** [commercialhaskell/stackage-nightly#5]
<img width="1440" alt="screen shot 2018-10-24 at 8 52 26 pm" src="https://user-images.githubusercontent.com/176723/47469500-31e39280-d7cf-11e8-8e83-662c733866a2.png">

**Comment by snoyberg** [comment]
Please run `stack upgrade`

**Comment by wanggang1** [comment]
that fixed it.  I'll close the issue.  thanks
