### ISSUE TITLE
nightly-2020-01-17 file erroneously truncated

### ISSUE THREAD

**Issue by infinisil** [commercialhaskell/stackage-nightly#6]
The [nightly-2020-01-17](https://github.com/commercialhaskell/stackage-nightly/blob/f6744e059395c3d5894a720ff57f5a0728d0ad5e/nightly-2020-01-17.yaml) file seems to be truncated to only 840 lines, ending with
https://github.com/commercialhaskell/stackage-nightly/blob/f6744e059395c3d5894a720ff57f5a0728d0ad5e/nightly-2020-01-17.yaml#L830-L840

I noticed this because I got an error while trying to use it:
```
update: Unable to parse Stackage snapshot nightly-2020-01-17: Error in $: Invalid SHA256: Control.Exception.Safe.throwString called with:

Unable to convert "845e0fb8e46b14b3a24781254e554b9b4c1925ca17b09b5d32ae6902" into SHA256: NotEnoughBytes
Called from:
  stringException (src/Stack/Types/PackageIdentifier.hs:136:27 in stack-1.9.3-4IYEzEQLnJy20hiS7eTmzh:Stack.Types.PackageIdentifier)
```

**Comment by snoyberg** [comment]
Not sure what happened there, but it should be fixed now. That said, using newer nightlies based on GHC 8.8 with Stack 1.9 and older is almost certainly going to lead to errors at some point.

**Comment by infinisil** [comment]
Awesome, thanks for the quick fix!
